### ISSUE TITLE
`Buffer is not defined` error when using in the browser.

### ISSUE THREAD

**Issue by hipstermojo** [Callidon/bloom-filters#56] opened 2022-04-11 08:23 UTC
Hi I was trying to create a `BloomFilter` instance in the browser and it keeps throwing the error `Buffer is not defined` error even though I'm only importing the `BloomFilter` export which doesn't use the Buffer class.

Is there a workaround for this?

I'm using the library with the vite bundler on firefox 99, if that helps.

**Comment by folkvir** [comment] 2022-04-11 09:54
Hi! Thank you for reporting. Is this the latest version?

**Comment by hipstermojo** [comment] 2022-04-11 09:58
yes it's on version 3.0.0

**Comment by folkvir** [comment] 2022-04-11 10:27
A browserify build succeeds for me for the 3.0.0.

`browserify -r ./dist/api.js:bloom-filters > bundle.js` with the following html file:
```html
<script src="./bundle.js"></script>
<script type="text/javascript">
  const { BloomFilter } = require('bloom-filters')
  const a = BloomFilter.create(2, 0.01)
  a.add(1)
  console.log("1: ", a.has(1))
</script>
```

**Comment by folkvir** [comment] 2022-04-11 10:34
Some polyfills are automatically added when using browserify such as the Buffer one. 
When importing the package you should import using the "bloom-filters/bloom/bloom-filter.js" syntax instead of `const = {...} = require('bloom-filters')` if you want only the BloomFilter class. Otherwise you'll get all the cose, and your compiler will surely stuck on the Buffer part used in other modules.

**Comment by folkvir** [comment] 2022-04-11 10:37
I close the issue since it is not a bug, feel free to continue the discussion!

**Closed by folkvir** 2022-04-11 10:37 UTC
